name: 'Documentation (Push Event)'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'docs/**'
    # NOTE: The tag push event isn't constrained by branch and path conditions.
    # For taking a snapshot of the docs state from the tagged commit,
    # to a versioned subdirectory with name matching the git tag substring `v<MAJOR>.<MINOR>`:
    tags:
      - 'v*'

# Jobs `run` steps will perform shell commands from this subdirectory:
defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    name: 'Deploy Docs'
    runs-on: ubuntu-20.04
    env:
      DOCS_VERSION: edge
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: 'Check if should deploy for `<major>.<minor>` tag version instead'
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          DOCS_VERSION=$(egrep -o 'v[0-9]+\.[0-9]+' <<< "${GITHUB_REF}")
          echo "DOCS_VERSION=${DOCS_VERSION}" >> $GITHUB_ENV

      - name: 'Deploy to Github Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build directory contents  to publish to `gh-pages` branch:
          publish_dir: ./docs/site
          # Directory to place `publish_dir` contents on the `gh-pages` branch:
          destination_dir: ${{ env.DOCS_VERSION }}
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
