name: 'Documentation'

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build:
    name: 'Verify Build'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: Preview Deploy (Netlify)
        id: preview
        uses: nwtgck/actions-netlify@v1.1
        timeout-minutes: 1
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: ./docs/site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Preview Deploy - ${{ github.event.pull_request.title }}
          alias: preview-for-pr-${{ github.event.pull_request.number }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            [Documentation preview for this PR](${{ steps.preview.outputs.deploy-url }}) is ready! :tada:

            Built with commit ${{ github.sha }}

