name: 'Documentation'

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build:
    name: 'Verify Build'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: Deploy Preview (Netlify)
        id: preview
        uses: nwtgck/actions-netlify@v1.1
        timeout-minutes: 1
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias: deploy-preview-${{ github.event.pull_request.number }}
          deploy-message: PR#${{ github.event.pull_request.number }}@${{ github.event.pull_request.head.sha }} | ${{ github.event.pull_request.title }}
          publish-dir: ./docs/site
          # We supply our own PR comment after this step.
          enable-pull-request-comment: false
          # Disable adding deploy comment on merge commit.
          enable-commit-comment: false
          # Disable adding a "Netlify - Netlify deployment" check status.
          # May be useful, can click the status symbol for past commits to view old previews?
          # enable-commit-status: false
          # production-deploy: false
          # netlify-config-path: ./docs/netlify.toml

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            [Documentation preview for this PR](${{ steps.preview.outputs.deploy-url }}) is ready! :tada:

            Built with commit ${{ github.event.pull_request.head.sha }}

