name: 'Docs - Preview Build'

on:
  pull_request:
    paths:
      - 'docs/**'

concurrency:
  group: deploy-preview-pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-preview:
    name: 'Build Preview'
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR: docs/site
      PREVIEW_PREFIX: pullrequest-${{ github.event.pull_request.number }}
      SITE_NAME: wonderful-liskov-8de2b1
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs
        run: |
          # Adjust mkdocs.yml for preview build
          sed -i "s|^site_url:.*|site_url: 'https://${PREVIEW_PREFIX}--${SITE_NAME}.netlify.app/'|" mkdocs.yml

          ../.github/workflows/scripts/docs/build-docs.sh

      # Minimize risk of failure by reducing to single file upload (tar) and bandwidth used (zstd)
      # Bundles build dir and env file into a zstd archive, nested file paths will be preserved.
      # Compress archive with zstd, default level 3 (fast) - output is ~10% of archive size.
      - name: 'Prepare artifact for transfer'
        run: |
          # Save ENV for transfer
          echo "PR_HEADSHA=${{ github.event.pull_request.head.sha }}" >> pr.env
          echo "PR_NUMBER=${{ github.event.pull_request.number }}"    >> pr.env
          echo "PR_TITLE=${{ github.event.pull_request.title }}"      >> pr.env
          echo "PREVIEW_PREFIX=${{ env.PREVIEW_PREFIX }}"             >> pr.env
          echo "BUILD_DIR=${{ env.BUILD_DIR }}"                       >> pr.env

          tar --zstd -cf artifact.tar.zst pr.env ${{ env.BUILD_DIR }}

      - name: 'Upload artifact for workflow transfer'
        uses: actions/upload-artifact@v2
        with:
          name: preview-build
          path: artifact.tar.zst
          retention-days: 1

