name: 'Documentation'

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-20.04
    env:
      PREVIEW_PREFIX: pullrequest-preview-${{ github.event.pull_request.number }}
      SITE_NAME: wonderful-liskov-8de2b1
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs
        run: |
          # Adjust mkdocs.yml for preview build
          sed -i "s|^site_url:.*|site_url: 'https://${PREVIEW_PREFIX}--${SITE_NAME}.netlify.app/'|" mkdocs.yml

          ../.github/workflows/scripts/docs/build-docs.sh

      - name: 'Send preview build to Netlify'
        id: preview
        uses: nwtgck/actions-netlify@v1.2
        timeout-minutes: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment-environment: netlify
          github-deployment-description: nwtgck-test
          fails-without-credentials: true
          alias: ${{ env.PREVIEW_PREFIX }}
          deploy-message: ${{ github.event.pull_request.title }}(PR#${{ github.event.pull_request.number }}@${{ github.event.pull_request.head.sha }})
          publish-dir: ./docs/site
          # We supply our own PR comment after this step.
          enable-pull-request-comment: false
          # Disable adding deploy comment on pre-merge commit.
          enable-commit-comment: false
          # Disable adding a "Netlify - Netlify deployment" check status.
          enable-commit-status: false
          # production-deploy: false
          # netlify-config-path: ./docs/netlify.toml

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            [Documentation preview for this PR](${{ steps.preview.outputs.deploy-url }}) is ready! :tada:

            Built with commit ${{ github.event.pull_request.head.sha }}

