name: 'Documentation (versions.json)'

# The creation of a branch will trigger this
on:
  create:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  add-version-to-docs:
    name: 'Update `gh-pages` branch `versions.json`'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout the default branch (master)'
        uses: actions/checkout@v2

      - name: 'Checkout the docs branch to a subdirectory'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      # Sets `DOCS_VERSION` env var, if invalid exits job early
      - name: 'Ensure `versions.json` has relevant `<major>.<minor>` tag version (truncates patch version)'
        working-directory: gh-pages
        run: '../.github/workflows/scripts/docs/update-versions-json.sh'

      # If an actual change was made, commit and push it, otherwise job will have exited.
      - name: 'Push update for `versions.json`'
        working-directory: gh-pages
        env:
          TEST: 'test'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add versions.json
          git commit -m "Make $DOCS_VERSION available $TEST to the 'mike' version selector"
          git push
