name: 'Documentation (versions.json)'

on:
  push:
    # NOTE: The tag push event cannot be constrained by `branches` and `paths` `on.push` conditions.
    tags:
      - 'v*'

jobs:
  add-version-to-docs:
    name: 'Update `gh-pages` branch `versions.json`'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout the default branch (master)'
        uses: actions/checkout@v2

      - name: 'Checkout the docs branch to a subdirectory'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      # Sets `DOCS_VERSION` env var, if invalid exits job early
      - name: 'Ensure `versions.json` has relevant `<major>.<minor>` tag version (truncates patch version)'
        working-directory: gh-pages
        run: |
          ../.github/workflows/scripts/docs/update-versions-json.sh
          DOCS_VERSION=$(egrep -o 'v[0-9]+\.[0-9]+' <<< "${GITHUB_REF}")
          echo "DOCS_VERSION=${DOCS_VERSION}" >> $GITHUB_ENV


      # If an actual change was made, commit and push it, otherwise job will have exited.
      - name: 'Push update for `versions.json`'
        working-directory: gh-pages
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add versions.json
          git commit -m "Make ${{ env.DOCS_VERSION }} available $GITHUB_ENV to the 'mike' version selector"
          git push
